[project]
name = "elevation-analysis"
version = "0.1.0"
description = "Quick overview of loading, viewing, and manipulating images"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "matplotlib>=3.7.0",
    "numpy>=1.24.0",
    "pillow>=10.0.0",
    "ipykernel>=6.25.0",
]
